# Generated by Django 3.0.4 on 2020-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='article title')),
                ('article_content', models.CharField(max_length=200, verbose_name='main content')),
                ('article_example', models.CharField(max_length=200)),
                ('article_date', models.DateTimeField(verbose_name='last mark')),
            ],
        ),
    ]
